language: cpp
os: osx
compiler:
  - clang
env:
  global:
    - DISPLAY=:99
  matrix:
    - GMOCK_VER=1.8.0 
    - GMOCK_VER=1.7.0 
install:
  - brew update && brew install ninja qt5
  - gem install bundler
  - bundle install

script: ./travis.sh

# default notifications: https://docs.travis-ci.com/user/notifications#Notifications
